# Generated by Django 5.1.2 on 2024-11-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carPlates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
