# Generated by Django 5.1.2 on 2024-11-14 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_carplates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateNumber', models.CharField(max_length=20, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_plates', to='profiles.profile')),
            ],
        ),
    ]
