# Generated by Django 5.1.2 on 2024-11-14 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='parkingLot',
        ),
        migrations.CreateModel(
            name='ParkingGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('slotNo', models.CharField(max_length=10, unique=True)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('row', 'column')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='parkingSlot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.parkinggrid'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ParkingLot',
        ),
    ]
